### ISSUE TITLE
Bug: new tiles are added even when the board hasn't changed

### ISSUE THREAD

**Issue by lolmaus** [lifeart/gxt-game-2048#1]
#### Description:

In the original game, keypresses that do not result in a board changing — do not produce new tiles. gxt-game-2048 does.

#### Steps to reproduce:

- Keep pressing the same direction again and again.

#### Expected behavior:

When all tiles reach the edge and cannot move or merge, no tiles are being added with subsequent keypresses.

#### Actual behavior:

When all tiles reach the edge and cannot move or merge, tiles continue being added with subsequent keypresses.

**Comment by lifeart** [comment]
Fix added, @lolmaus thank you for report!
